steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/linuxtips-392717/minha-aplicacao-node', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/linuxtips-392717/minha-aplicacao-node']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'meu-teste-tres'
      - '--image=gcr.io/linuxtips-392717/minha-aplicacao-node:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY
  
