steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/linuxtips-392717/hello-repo/cicd-teste:1.0', '.']
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/linuxtips-392717/hello-repo/cicd-teste:1.0']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/helloworld-gke', 'hello-app=us-central1-docker.pkg.dev/linuxtips-392717/hello-repo/cicd-teste:1.0']
    env:
      - CLOUDSDK_CONTAINER_CLUSTER=linuxtips
      - CLOUDSDK_COMPUTE_ZONE=us-central1-a
      - CLOUDSDK_COMPUTE_REGION=us-central1
options:
  logging: CLOUD_LOGGING_ONLY