name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Build and Push Docker Image
      uses: google-github-actions/build-and-push-gke-container@v0
      with:
        image: eu.artifacts.${{ secrets.PROJECT_ID }}.appspot.com/linuxtips/my-node-app:${{ github.sha }}
        gcp_project_id: ${{ secrets.PROJECT_ID }}
        gcp_location: us-central1

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-node-app \
          --image gcr.io/${{ secrets.PROJECT_ID }}/my-node-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
