name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Authenticate with Container Registry
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.PROJECT_ID }}/my-node-app .
        docker push gcr.io/${{ secrets.PROJECT_ID }}/my-node-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-node-app \
          --image gcr.io/${{ secrets.PROJECT_ID }}/my-node-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
